[update]
tasks = ["interfaces"]

[update.interfaces]
paths = ["QRCodeGen", "QRCodeGen Extension"]
defaultToBase = true
ignoreEmptyStrings = true
unstripped = false

[update.code]
codePaths = ["QRCodeGen", "QRCodeGen Extension"]
localizablePaths = ["QRCodeGen", "QRCodeGen Extension"]
defaultToKeys = true
additive = true
unstripped = false
plistArguments = true

[update.transform]
codePaths = ["QRCodeGen", "QRCodeGen Extension"]
localizablePaths = ["QRCodeGen", "QRCodeGen Extension"]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = ["QRCodeGen", "QRCodeGen Extension"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["QRCodeGen", "QRCodeGen Extension"]
duplicateKeys = true
emptyValues = true
